### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by 1837620622** [CPScript/DDoS-ToolKit#1]
能给几个指令吗

**Comment by 0u44** [comment]
是的！我会尽快把它们放到github项目中

**Comment by 1837620622** [comment]
今天可以吗&nbsp;&nbsp;


***@***.***
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月12日(星期一) 凌晨0:48
收件人: ***@***.***&gt;; 
抄送: ***@***.******@***.***&gt;; ***@***.***&gt;; 
主题: Re: [CPScript/DDoS-ToolKit] how to use (Issue #1)





 
是的！我会尽快把它们放到github项目中

**Comment by 0u44** [comment]
完毕
